# Backend API - Development Environment

replicaCount: 1

image:
  repository: myregistry/backend-api
  tag: "dev-latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

env:
  - name: ENVIRONMENT
    value: "development"
  - name: LOG_LEVEL
    value: "debug"
  - name: DATABASE_URL
    value: "postgresql://postgres:5432/myapp"
  - name: REDIS_URL
    value: "redis://redis-standalone.cache.svc.cluster.local:6379"

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

serviceMonitor:
  enabled: false
