{{- if .Values.primary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-primary
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
    component: primary
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: metrics
      port: 9187
      targetPort: 9187
  clusterIP: None
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
    component: primary
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.fullname" . }}-primary
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
    component: primary
spec:
  serviceName: {{ include "postgres.fullname" . }}-primary
  replicas: {{ .Values.primary.replicas }}
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
      component: primary
  template:
    metadata:
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
        component: primary
    spec:
      serviceAccountName: {{ include "postgres.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-permissions
          image: busybox:1.36
          command: ['sh', '-c', 'chown -R 999:999 /var/lib/postgresql/data || true']
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          securityContext:
            runAsUser: 0
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.user }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgres.fullname" . }}-secrets
                  key: postgres-user
            - name: POSTGRES_DB
              value: {{ .Values.database.name }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/00_init.sql
              subPath: 00_init.sql
            - name: pg-hba
              mountPath: /etc/postgresql/pg_hba.conf
              subPath: pg_hba.conf
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.database.user }} -h localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.database.user }} -h localhost
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.primary.resources | nindent 12 }}
        {{- if .Values.monitoring.enabled }}
        - name: postgres-exporter
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://{{ .Values.database.user }}:$(POSTGRES_PASSWORD)@localhost:5432/{{ .Values.database.name }}?sslmode=disable"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgres.fullname" . }}-secrets
                  key: postgres-user
          resources:
            {{- toYaml .Values.exporter.resources | nindent 12 }}
        {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: init-sql
          configMap:
            name: {{ include "postgres.fullname" . }}-init-sql
        - name: pg-hba
          configMap:
            name: {{ include "postgres.fullname" . }}-pg-hba
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.primary.storage.storageClass }}
        storageClassName: {{ .Values.primary.storage.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.primary.storage.size }}
{{- end }}
