{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      {{- range .Values.networkPolicy.allowedNamespaces }}
      - namespaceSelector:
          matchLabels:
            name: {{ . }}
      {{- end }}
      ports:
      - protocol: TCP
        port: 6379
      {{- if eq .Values.mode "cluster" }}
      - protocol: TCP
        port: 16379
      {{- end }}
      {{- if .Values.monitoring.enabled }}
      - protocol: TCP
        port: 9121
      {{- end }}
  egress:
    - to:
      - namespaceSelector: {}
      ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
    - to:
      - podSelector:
          matchLabels:
            {{- include "redis.selectorLabels" . | nindent 12 }}
{{- end }}
