apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  mysql-user: {{ .Values.auth.username | b64enc | quote }}
  mysql-password: {{ .Values.auth.password | b64enc | quote }}
  {{- if .Values.replication.enabled }}
  mysql-replication-user: {{ .Values.auth.replicationUser | b64enc | quote }}
  mysql-replication-password: {{ .Values.auth.replicationPassword | b64enc | quote }}
  {{- end }}
