apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secrets
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-user: {{ .Values.secrets.postgresPassword | required "secrets.postgresPassword is required" }}
  postgres-replicator: {{ .Values.secrets.replicatorPassword | required "secrets.replicatorPassword is required" }}
