{{- if .Values.cronJobs.enabled }}
{{- range .Values.cronJobs.list }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "helm-app.fullname" $ }}-{{ .name }}
  labels:
    {{- include "helm-app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: cronjob
spec:
  schedule: {{ .schedule | quote }}
  {{- with .concurrencyPolicy }}
  concurrencyPolicy: {{ . }}
  {{- end }}
  {{- with .successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with .failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "helm-app.selectorLabels" $ | nindent 12 }}
            app.kubernetes.io/component: cronjob
        spec:
          restartPolicy: {{ .restartPolicy | default "OnFailure" }}
          containers:
            - name: {{ .name }}
              image: {{ .image }}
              {{- with .command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .env }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
{{- end }}
{{- end }}
