# Backend API - Production Environment

replicaCount: 4

image:
  repository: myregistry/backend-api
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

env:
  - name: ENVIRONMENT
    value: "production"
  - name: LOG_LEVEL
    value: "info"
  - name: DATABASE_URL
    value: "postgresql://postgres-primary.db.svc.cluster.local:5432/myapp"
  - name: REDIS_URL
    value: "redis://redis-cluster.cache.svc.cluster.local:6379"

secrets:
  enabled: true
  data:
    dbPassword: "CHANGE_ME_IN_PRODUCTION"
    apiKey: "CHANGE_ME_IN_PRODUCTION"

resources:
  requests:
    cpu: 1
    memory: 2Gi
  limits:
    cpu: 2
    memory: 4Gi

livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 2

podAntiAffinity:
  enabled: true
  type: soft

serviceMonitor:
  enabled: true
  interval: 30s
  path: /metrics

prometheusRule:
  enabled: true
  rules:
    - alert: BackendHighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Backend API high error rate
        description: Error rate is above 5% for 5 minutes

networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: myapp
        - podSelector:
            matchLabels:
              app: frontend
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: db
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - namespaceSelector:
            matchLabels:
              name: cache
      ports:
        - protocol: TCP
          port: 6379
