# Worker Service - Production Environment

replicaCount: 3

image:
  repository: myregistry/worker
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

env:
  - name: ENVIRONMENT
    value: "production"
  - name: DATABASE_URL
    value: "postgresql://postgres-primary.db.svc.cluster.local:5432/myapp"
  - name: KAFKA_BROKERS
    value: "kafka-0.kafka.queue.svc.cluster.local:9092,kafka-1.kafka.queue.svc.cluster.local:9092,kafka-2.kafka.queue.svc.cluster.local:9092"

resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 2
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 2

serviceMonitor:
  enabled: true
