apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  mongodb-user: {{ .Values.auth.username | b64enc | quote }}
  mongodb-password: {{ .Values.auth.password | b64enc | quote }}
  {{- if .Values.replicaSet.enabled }}
  mongodb-replica-set-key: {{ .Values.replicaSet.key | b64enc | quote }}
  {{- end }}
