{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helm-app.fullname" . }}
  labels:
    release: prometheus
    app: {{ include "helm-app.name" . }}
    environment: {{ .Values.env.ENVIRONMENT }}
spec:
  selector:
    matchLabels:
      app: {{ include "helm-app.name" . }}
      environment: {{ .Values.env.ENVIRONMENT }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }} 